from pathlib import Path

from copilot_plugin_manager.catalog import load_catalog_bundle
from copilot_plugin_manager.manager import PluginManager
from copilot_plugin_manager.models import SourceState
from copilot_plugin_manager.paths import ManagerPaths
from copilot_plugin_manager.runner import CommandResult, ShellRunner


class FakeRunner(ShellRunner):
    def __init__(self) -> None:
        self.calls: list[tuple[str, ...]] = []

    def require(self, name: str) -> None:
        return None

    def run(
        self,
        args: list[str],
        cwd: Path | None = None,
        check: bool = True,
    ) -> CommandResult:
        self.calls.append(tuple(args))
        return CommandResult(
            tuple(args),
            "Installed plugins:\n  • awesome-copilot@awesome-copilot (v1.0.0)\n",
            "",
            0,
        )


def test_plugin_actions_for_switch_non_exclusive() -> None:
    manager = PluginManager(
        load_catalog_bundle(),
        ManagerPaths(
            Path("/tmp/.copilot"),
            Path("/tmp/.copilot/copilot-plugin-manager"),
            Path("/tmp/.copilot/skills"),
            Path("/tmp/.copilot/agents"),
            Path("/tmp/.copilot/active-profile"),
            Path("/tmp/.copilot/copilot-plugin-manager/state.json"),
            Path("/tmp/.copilot/copilot-plugin-manager/sources"),
        ),
        runner=FakeRunner(),
    )
    actions = manager.plugin_actions_for_switch("minimal", ["awesome-copilot", "partners"], exclusive=False)
    commands = [action.command for action in actions]
    assert ("copilot", "plugin", "uninstall", "partners") in commands
    assert ("copilot", "plugin", "install", "context-engineering@awesome-copilot") in commands


def test_sync_skill_provider_from_submodule_layout(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setenv("COPILOT_HOME", str(tmp_path / ".copilot"))
    bundle = load_catalog_bundle()
    paths = ManagerPaths.from_environment()
    runner = FakeRunner()
    manager = PluginManager(bundle, paths, runner=runner)

    project = tmp_path / "repo"
    source_root = project / "external" / "anthropics-skills" / "skills" / "pdf" / "sample-skill"
    source_root.mkdir(parents=True)
    (source_root / "README.md").write_text("sample")

    manager.sync_skill_provider("anthropic-pdf", project)

    assert (paths.skills_dir / "anthropic-pdf__sample-skill").exists()


def test_sync_agent_provider_normalizes_output_name_and_metadata(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setenv("COPILOT_HOME", str(tmp_path / ".copilot"))
    bundle = load_catalog_bundle()
    paths = ManagerPaths.from_environment()
    manager = PluginManager(bundle, paths, runner=FakeRunner())

    project = tmp_path / "repo"
    source_file = project / "external" / "agency-agents" / "design" / "design-brand-guardian.md"
    source_file.parent.mkdir(parents=True)
    source_file.write_text("# Design Brand Guardian\\n\\nHelps with brand systems.\\n")

    manager.sync_agent_provider("agency-design-brand-guardian", project)

    generated = paths.agents_dir / "agency-design-brand-guardian__design__design-brand-guardian.agent.md"
    assert generated.exists()
    content = generated.read_text()
    assert "Generated by copilot-plugin-manager." in content
    assert content.startswith("<!--")
    assert "commit_revision:" in content
    assert "# Design Brand Guardian" in content


def test_sync_missing_agent_providers_dedupes_overlapping_sources(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setenv("COPILOT_HOME", str(tmp_path / ".copilot"))
    bundle = load_catalog_bundle()
    paths = ManagerPaths.from_environment()
    manager = PluginManager(bundle, paths, runner=FakeRunner())

    project = tmp_path / "repo"
    source_file = project / "external" / "agency-agents" / "design" / "design-brand-guardian.md"
    source_file.parent.mkdir(parents=True)
    source_file.write_text("# Design Brand Guardian\n\nHelps with brand systems.\n")

    manager.sync_agent_provider("agency", project)
    broad_output = paths.agents_dir / "agency__design__design-brand-guardian.agent.md"
    assert broad_output.exists()

    manager._sync_missing_agent_providers(["agency", "agency-design-brand-guardian"], project)

    leaf_output = paths.agents_dir / "agency-design-brand-guardian__design__design-brand-guardian.agent.md"
    assert leaf_output.exists()
    assert not broad_output.exists()


def test_probe_manifest_version_supports_generic_manifests(tmp_path: Path) -> None:
    manager = PluginManager(
        load_catalog_bundle(),
        ManagerPaths(
            Path("/tmp/.copilot"),
            Path("/tmp/.copilot/copilot-plugin-manager"),
            Path("/tmp/.copilot/skills"),
            Path("/tmp/.copilot/agents"),
            Path("/tmp/.copilot/active-profile"),
            Path("/tmp/.copilot/copilot-plugin-manager/state.json"),
            Path("/tmp/.copilot/copilot-plugin-manager/sources"),
        ),
        runner=FakeRunner(),
    )

    package_root = tmp_path / "package"
    package_root.mkdir()
    (package_root / "package.json").write_text('{"name":"demo","version":"1.2.3"}')

    pyproject_root = tmp_path / "pyproject"
    pyproject_root.mkdir()
    (pyproject_root / "pyproject.toml").write_text('[project]\nname = "demo"\nversion = "2.0.0"\n')

    assert manager.probe_manifest_version(package_root) == "1.2.3"
    assert manager.probe_manifest_version(pyproject_root) == "2.0.0"


def test_source_state_compares_by_revision_before_manifest_version() -> None:
    previous = SourceState(revision="abc123", manifest_version="1.0.0")
    same_revision_newer_manifest = SourceState(revision="abc123", manifest_version="2.0.0")
    changed_revision = SourceState(revision="def456", manifest_version="1.0.0")
    manifest_only_change = SourceState(manifest_version="2.0.0")

    assert same_revision_newer_manifest.has_comparable_change(previous) is False
    assert changed_revision.has_comparable_change(previous) is True
    assert manifest_only_change.has_comparable_change(SourceState(manifest_version="1.0.0")) is True
