from __future__ import annotations

from pathlib import Path

from .catalog import CatalogBundle, load_catalog_bundle

README_SECTION_START = "<!-- generated:catalog-overview:start -->"
README_SECTION_END = "<!-- generated:catalog-overview:end -->"


def _inline_codes(values: list[str]) -> str:
    return ", ".join(f"`{value}`" for value in values) if values else "none"


def render_readme_section(bundle: CatalogBundle) -> str:
    lines = [
        "_This section is generated from the bundled catalog data with `uv run poe generate-docs`._",
        "",
        f"- `{len(bundle.profiles)}` profiles",
        f"- `{len(bundle.themes)}` themes",
        f"- `{len(bundle.plugins)}` plugins",
        f"- `{len(bundle.skill_providers)}` skill providers",
        f"- `{len(bundle.agent_providers)}` agent providers",
        "",
        "See also:",
        "- [`docs/THEMES.md`](docs/THEMES.md) for the full theme and profile composition reference.",
        "- [`docs/CREDITS.md`](docs/CREDITS.md) for upstream catalog credits.",
        "",
        "### Current profile compositions",
        "",
        "| Profile | Themes |",
        "| --- | --- |",
    ]
    lines.extend(f"| `{name}` | {_inline_codes(profile.themes)} |" for name, profile in bundle.profiles.items())
    return "\n".join(lines).rstrip() + "\n"


def render_credits_markdown(bundle: CatalogBundle) -> str:
    lines = [
        "# Credits",
        "",
        "_Generated by `uv run poe generate-docs`. Do not edit manually._",
        "",
        "These bundled catalogs build on the upstream repositories tracked by this project.",
        "",
        "| Source | Owner / Repo | License | Providers | Files | Description |",
        "| --- | --- | --- | ---: | ---: | --- |",
    ]
    for name in bundle.repositories:
        metadata = bundle.repository_metadata(name)
        summary = bundle.source_entrypoint_summary(name)
        lines.append(f"| `{name}` | `{metadata['owner_repo']}` | {metadata['license']} | {summary['provider_count']} | {summary['file_count']} | {metadata['description']} |")
    lines.extend(
        [
            "",
            "## Repository details",
            "",
        ]
    )
    for name in bundle.repositories:
        metadata = bundle.repository_metadata(name)
        lines.extend(
            [
                f"### `{name}`",
                "",
                f"- URL: <{metadata['url']}>",
                f"- Submodule path: `{metadata['submodule_path']}`",
                f"- Tags: {metadata['tags']}",
                f"- Use when: {metadata['use_when']}",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def render_themes_markdown(bundle: CatalogBundle) -> str:
    lines = [
        "# Themes and profile compositions",
        "",
        "_Generated by `uv run poe generate-docs`. Do not edit manually._",
        "",
        "## Summary",
        "",
        f"- `{len(bundle.profiles)}` profiles",
        f"- `{len(bundle.themes)}` themes",
        f"- `{len(bundle.plugins)}` plugins",
        f"- `{len(bundle.skill_providers)}` skill providers",
        f"- `{len(bundle.agent_providers)}` agent providers",
        "",
        "## Profiles",
        "",
        "| Profile | Themes | Plugins | Skills | Agents |",
        "| --- | --- | ---: | ---: | ---: |",
    ]
    for name, profile in bundle.profiles.items():
        lines.append(
            f"| `{name}` | {_inline_codes(profile.themes)} | "
            f"{len(bundle.target_items(profile.themes, 'plugins'))} | "
            f"{len(bundle.target_items(profile.themes, 'skills'))} | "
            f"{len(bundle.target_items(profile.themes, 'agents'))} |"
        )
    lines.extend(
        [
            "",
            "## Themes",
            "",
        ]
    )
    for name, theme in bundle.themes.items():
        lines.extend(
            [
                f"### `{name}`",
                "",
                f"- Plugins ({len(theme.plugins)}): {_inline_codes(theme.plugins)}",
                f"- Skills ({len(theme.skills)}): {_inline_codes(theme.skills)}",
                f"- Agents ({len(theme.agents)}): {_inline_codes(theme.agents)}",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def update_readme_generated_section(readme_text: str, bundle: CatalogBundle) -> str:
    if README_SECTION_START not in readme_text or README_SECTION_END not in readme_text:
        raise ValueError("README.md is missing the generated catalog overview markers.")
    before, _, remainder = readme_text.partition(README_SECTION_START)
    _, _, after = remainder.partition(README_SECTION_END)
    section = f"{README_SECTION_START}\n{render_readme_section(bundle).rstrip()}\n{README_SECTION_END}"
    return before + section + after


def write_catalog_docs(project_root: Path, bundle: CatalogBundle | None = None) -> list[Path]:
    bundle = bundle or load_catalog_bundle()
    docs_dir = project_root / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)

    credits_path = docs_dir / "CREDITS.md"
    themes_path = docs_dir / "THEMES.md"
    readme_path = project_root / "README.md"

    credits_path.write_text(render_credits_markdown(bundle), encoding="utf-8")
    themes_path.write_text(render_themes_markdown(bundle), encoding="utf-8")
    readme_path.write_text(update_readme_generated_section(readme_path.read_text(encoding="utf-8"), bundle), encoding="utf-8")

    return [credits_path, themes_path, readme_path]
